### ISSUE TITLE
Add lints section to Cargo.toml

### ISSUE THREAD

**Issue by bouzuya** [bouzuya/serde-firestore-value#5]
```toml
[lints.rust]
missing_docs = "deny"

[lints.rustdoc]
all = "deny"
```
